name: Cart Service
on:
  push:
    paths:
      - cart-service/**
    branches:
      - '**'
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      working-directory: ./cart-service
      DOCKER_IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/bookstore-cart-service
    defaults:
      run:
        working-directory: ${{ env.working-directory }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'
      - name: Grant execute permission for Maven Wrapper
        run: chmod +x ./mvnw
      - name: Set up Testcontainers reuse
        run: echo "testcontainers.reuse.enable=true" > ~/.testcontainers.properties
      - name: Set environment variable to skip test
        run: echo "SKIP_ADD_TO_CART_TEST=true" >> $GITHUB_ENV
      - name: Build with Maven
        run: ./mvnw -ntp verify
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and Publish Docker Image
        run: |
          ./mvnw spring-boot:build-image -DskipTests
          echo "Pushing the image $DOCKER_IMAGE_NAME to Docker Hub..."
          docker push $DOCKER_IMAGE_NAME